// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

#pragma once

/** @file gdb_printers.hpp
 * @brief Embeds GDB pretty printers for microfmt types into the binary.
 *
 * Including this header anywhere in a program (typically once, from the
 * translation unit containing `main`) embeds the full contents of
 * `tools/gdb/microfmt_printers.py` into a `.debug_gdb_scripts` section via
 * inline assembly. When the resulting binary is loaded in GDB, GDB
 * auto-loads and runs that script, registering pretty printers for every
 * microfmt sink/buffer/logger type -- no `source` command, no
 * `<binary>-gdb.py` file, and no `sys.path` setup required.
 *
 * This still requires GDB's `auto-load safe-path` to include the path of
 * the binary containing this section (GDB disables auto-loading from
 * untrusted locations by default); see
 * https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html
 *
 * This file is generated by `tools/gdb/generate_embedded_header.py` from
 * `tools/gdb/microfmt_printers.py` -- do not hand-edit it. Regenerate it
 * whenever the printer script changes.
 *
 * Embedding costs a copy of the (small) Python source in every
 * translation unit that includes this header for a *distinct* binary;
 * the `"MS"` section flags let the linker fold identical copies within
 * the same binary into one, so including it from multiple translation
 * units of the same program is free.
 *
 * The `.debug_gdb_scripts` mechanism relies on GNU-assembler inline `asm`
 * syntax and is only meaningful to GDB, so this header is a silent no-op
 * -- it defines nothing and emits no section -- on compilers other than
 * Clang/GCC (e.g. MSVC). Guarded on `__clang__`/`__GNUC__` rather than
 * platform, so it also no-ops under `clang-cl`, which defines `_MSC_VER`
 * but not GNU inline-asm syntax in its default mode.
 */

#if defined(__clang__) || defined(__GNUC__)

// clang-format off
asm(
    ".pushsection \".debug_gdb_scripts\", \"MS\",@progbits,1\n"
    ".byte 4\n" /* SECTION_SCRIPT_ID_PYTHON_TEXT */
    ".ascii \"microfmt-pretty-printers.py\\n# SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>\"\n"
    ".ascii \"\\n#\\n# SPDX-License-Identifier: BSD-2-Clause\\n\\n\\\"\\\"\\\"GDB pretty printers for the microfmt header-only \"\n"
    ".ascii \"library.\\n\\nThis module can be used in three interchangeable ways:\\n\\n  1. Sourced directly in a run\"\n"
    ".ascii \"ning GDB session::\\n\\n         (gdb) source /path/to/microfmt/tools/gdb/microfmt_printers.py\\n\\n  2.\"\n"
    ".ascii \" Auto-loaded for a specific binary by placing a ``<binary>-gdb.py``\\n     next to it (or anywhere\"\n"
    ".ascii \" on GDB's auto-load path) containing::\\n\\n         import sys\\n         sys.path.insert(0, \\\"/path/t\"\n"
    ".ascii \"o/microfmt/tools/gdb\\\")\\n         import microfmt_printers\\n         microfmt_printers.register_mic\"\n"
    ".ascii \"rofmt_printers()\\n\\n  3. Embedded directly into the binary's ``.debug_gdb_scripts`` section via\\n  \"\n"
    ".ascii \"   ``include/microfmt/gdb_printers.hpp`` (see that header for details); GDB\\n     then loads and \"\n"
    ".ascii \"runs this exact source automatically when the binary is\\n     loaded, with no external file or pa\"\n"
    ".ascii \"th configuration required.\\n\\nIn all three cases the printers are registered against ``objfile`` (\"\n"
    ".ascii \"or the\\nglobal printer list, when there is no current object file) the moment this\\nmodule is load\"\n"
    ".ascii \"ed -- see the bottom of the file.\\n\\nType-erased sinks/views whose stored data can only be recover\"\n"
    ".ascii \"ed by calling\\nthrough a function pointer or an externally-owned abstract interface (e.g.\\n``micro\"\n"
    ".ascii \"fmt::sink``, ``microfmt::format_args``, ``microfmt::sinks::sbuf_sink``)\\nare intentionally not co\"\n"
    ".ascii \"vered: invoking that callback from GDB's Python API\\nisn't reliably callable, and they add little\"\n"
    ".ascii \" value over default struct\\nprinting.\\n\\\"\\\"\\\"\\n\\ntry:\\n    import gdb\\n    import gdb.printing\\nexcept Imp\"\n"
    ".ascii \"ortError:  # pragma: no cover - only importable inside GDB.\\n    gdb = None\\n\\n\\ndef _char_pointer_s\"\n"
    ".ascii \"tring(ptr_val, length):\\n    \\\"\\\"\\\"Renders a ``char*`` + length pair the way GDB renders C strings.\\\"\"\n"
    ".ascii \"\\\"\\\"\\n    if length == 0:\\n        return '\\\"\\\"'\\n    try:\\n        return ptr_val.lazy_string(length=in\"\n"
    ".ascii \"t(length))\\n    except gdb.error:\\n        return \\\"<unreadable>\\\"\\n\\n\\nclass MicrofmtSpanSinkPrinter:\\n\"\n"
    ".ascii \"    \\\"\\\"\\\"Pretty printer for `microfmt::span_sink`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.v\"\n"
    ".ascii \"al = val\\n\\n    def to_string(self):\\n        buf = self.val[\\\"m_buf\\\"]\\n        pos = int(self.val[\\\"m\"\n"
    ".ascii \"_pos\\\"])\\n        cap = int(buf[\\\"m_size\\\"])\\n        return \\\"microfmt::span_sink written %d of %d by\"\n"
    ".ascii \"tes = %s\\\" % (\\n            pos,\\n            cap,\\n            _char_pointer_string(buf[\\\"m_ptr\\\"], p\"\n"
    ".ascii \"os),\\n        )\\n\\n\\nclass MicrofmtBufferSinkPrinter:\\n    \\\"\\\"\\\"Pretty printer for `microfmt::buffer_si\"\n"
    ".ascii \"nk<N>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n      \"\n"
    ".ascii \"  capacity = int(self.val.type.template_argument(0))\\n        pos = int(self.val[\\\"m_pos\\\"])\\n      \"\n"
    ".ascii \"  return \\\"microfmt::buffer_sink written %d of %d bytes = %s\\\" % (\\n            pos,\\n            ca\"\n"
    ".ascii \"pacity,\\n            _char_pointer_string(self.val[\\\"m_data\\\"], pos),\\n        )\\n\\n\\nclass MicrofmtCSt\"\n"
    ".ascii \"ringSinkPrinter:\\n    \\\"\\\"\\\"Pretty printer for `microfmt::c_string_sink<N>`.\\\"\\\"\\\"\\n\\n    def __init__(se\"\n"
    ".ascii \"lf, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        pos = int(self.val[\\\"m_pos\\\"])\\n\"\n"
    ".ascii \"        max_payload = int(self.val[\\\"m_max_payload\\\"])\\n        return \\\"microfmt::c_string_sink wri\"\n"
    ".ascii \"tten %d of %d bytes = %s\\\" % (\\n            pos,\\n            max_payload,\\n            _char_pointe\"\n"
    ".ascii \"r_string(self.val[\\\"m_data\\\"], pos),\\n        )\\n\\n\\nclass MicrofmtCStringSpanSinkPrinter:\\n    \\\"\\\"\\\"Pret\"\n"
    ".ascii \"ty printer for `microfmt::c_string_span_sink`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val\"\n"
    ".ascii \" = val\\n\\n    def to_string(self):\\n        data = self.val[\\\"m_data\\\"]\\n        pos = int(self.val[\\\"m\"\n"
    ".ascii \"_pos\\\"])\\n        max_payload = int(self.val[\\\"m_max_payload\\\"])\\n        if int(data) == 0:\\n        \"\n"
    ".ascii \"    return \\\"microfmt::c_string_span_sink [discarding, no buffer]\\\"\\n        return \\\"microfmt::c_st\"\n"
    ".ascii \"ring_span_sink written %d of %d bytes = %s\\\" % (\\n            pos,\\n            max_payload,\\n      \"\n"
    ".ascii \"      _char_pointer_string(data, pos),\\n        )\\n\\n\\nclass MicrofmtCountingSinkPrinter:\\n    \\\"\\\"\\\"Pre\"\n"
    ".ascii \"tty printer for `microfmt::counting_sink`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = v\"\n"
    ".ascii \"al\\n\\n    def to_string(self):\\n        return \\\"microfmt::counting_sink counted %d byte(s)\\\" % int(s\"\n"
    ".ascii \"elf.val[\\\"m_count\\\"])\\n\\n\\nclass MicrofmtIteratorSinkPrinter:\\n    \\\"\\\"\\\"Pretty printer for `microfmt::it\"\n"
    ".ascii \"erator_sink<OutputIt>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_stri\"\n"
    ".ascii \"ng(self):\\n        return \\\"microfmt::iterator_sink at %s\\\" % str(self.val[\\\"m_it\\\"])\\n\\n\\nclass Microfm\"\n"
    ".ascii \"tMemoryBufferPrinter:\\n    \\\"\\\"\\\"Pretty printer for `microfmt::memory_buffer<N>` (and its base class\"\n"
    ".ascii \").\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        siz\"\n"
    ".ascii \"e = int(self.val[\\\"m_size\\\"])\\n        capacity = int(self.val[\\\"m_capacity\\\"])\\n        return \\\"micro\"\n"
    ".ascii \"fmt::memory_buffer of length %d, capacity %d = %s\\\" % (\\n            size,\\n            capacity,\\n \"\n"
    ".ascii \"           _char_pointer_string(self.val[\\\"m_data\\\"], size),\\n        )\\n\\n\\nclass MicrofmtLoggerPrint\"\n"
    ".ascii \"er:\\n    \\\"\\\"\\\"Pretty printer for `microfmt::log::basic_logger<MaxSinks, MsgBufferCapacity>`.\\\"\\\"\\\"\\n\\n  \"\n"
    ".ascii \"  def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        name = self.\"\n"
    ".ascii \"val[\\\"name_\\\"]\\n        level = self.val[\\\"level_\\\"]\\n        sink_count = int(self.val[\\\"sink_count_\\\"]\"\n"
    ".ascii \")\\n        return \\\"microfmt::log::basic_logger %s level=%s sinks=%d\\\" % (\\n            _char_pointe\"\n"
    ".ascii \"r_string(name[\\\"data_\\\"], name[\\\"size_\\\"]),\\n            str(level),\\n            sink_count,\\n        \"\n"
    ".ascii \")\\n\\n\\ndef _build_pretty_printer():\\n    pp = gdb.printing.RegexpCollectionPrettyPrinter(\\\"microfmt\\\")\"\n"
    ".ascii \"\\n    pp.add_printer(\\\"microfmt::span_sink\\\", r\\\"^microfmt::span_sink$\\\", MicrofmtSpanSinkPrinter)\\n  \"\n"
    ".ascii \"  pp.add_printer(\\\"microfmt::buffer_sink\\\", r\\\"^microfmt::buffer_sink<.*>$\\\", MicrofmtBufferSinkPrin\"\n"
    ".ascii \"ter)\\n    pp.add_printer(\\\"microfmt::c_string_sink\\\", r\\\"^microfmt::c_string_sink<.*>$\\\", MicrofmtCSt\"\n"
    ".ascii \"ringSinkPrinter)\\n    pp.add_printer(\\n        \\\"microfmt::c_string_span_sink\\\", r\\\"^microfmt::c_stri\"\n"
    ".ascii \"ng_span_sink$\\\", MicrofmtCStringSpanSinkPrinter\\n    )\\n    pp.add_printer(\\\"microfmt::counting_sink\"\n"
    ".ascii \"\\\", r\\\"^microfmt::counting_sink$\\\", MicrofmtCountingSinkPrinter)\\n    pp.add_printer(\\\"microfmt::iter\"\n"
    ".ascii \"ator_sink\\\", r\\\"^microfmt::iterator_sink<.*>$\\\", MicrofmtIteratorSinkPrinter)\\n    pp.add_printer(\\\"m\"\n"
    ".ascii \"icrofmt::memory_buffer\\\", r\\\"^microfmt::(detail::)?memory_buffer(_base)?(<.*>)?$\\\",\\n               \"\n"
    ".ascii \"     MicrofmtMemoryBufferPrinter)\\n    pp.add_printer(\\n        \\\"microfmt::log::basic_logger\\\", r\\\"^\"\n"
    ".ascii \"microfmt::log::basic_logger<.*>$\\\", MicrofmtLoggerPrinter\\n    )\\n    return pp\\n\\n\\ndef register_micr\"\n"
    ".ascii \"ofmt_printers(objfile=None):\\n    \\\"\\\"\\\"Registers the microfmt pretty printers with GDB.\\n\\n    Idempo\"\n"
    ".ascii \"tent: re-registering (e.g. because this module was sourced twice,\\n    or embedded in several obj\"\n"
    ".ascii \"ect files) simply replaces the previous\\n    registration under the same name.\\n    \\\"\\\"\\\"\\n    if gdb\"\n"
    ".ascii \" is None:\\n        return\\n\\n    target = objfile if objfile is not None else gdb\\n    gdb.printing.\"\n"
    ".ascii \"register_pretty_printer(target, _build_pretty_printer(), replace=True)\\n\\n\\nif gdb is not None:\\n   \"\n"
    ".ascii \" register_microfmt_printers(gdb.current_objfile())\\n\"\n"
    ".byte 0\n"
    ".popsection\n"
);
// clang-format on

#endif // defined(__clang__) || defined(__GNUC__)
